# Generated by Django 4.1.7 on 2023-05-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BlogRiverPlate", "0002_avatar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Avatar",
        ),
    ]
